### ISSUE TITLE
Web Scraping Youtube Playlist Information

### ISSUE THREAD

**Issue by trejoberriel** [scrapy/cssselect#107]
Im trying to extract information from Youtube but when I try to parse an element:

URL = "https://www.youtube.com/user/Urbanroosters/playlists"
with HTMLSession() as session:  
    request = session.get(URL)
    

body = request.html.find('div id="items" class="style-scope ytd-grid-renderer"><ytd-grid-playlist-renderer class="style-scope ytd-grid-renderer" lockup=""')

the following error is displayed:

Traceback (most recent call last):

  File "/Users/JGTB/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-138-29cbe5ab5d28>", line 7, in <module>
    body = request.html.find('div id="items" class="style-scope ytd-grid-renderer"><ytd-grid-playlist-renderer class="style-scope ytd-grid-renderer" lockup=""')

  File "/Users/JT/opt/anaconda3/lib/python3.7/site-packages/requests_html.py", line 212, in find
    for found in self.pq(selector)

  File "/Users/JGTB/opt/anaconda3/lib/python3.7/site-packages/pyquery/pyquery.py", line 300, in __call__
    result = self._copy(*args, parent=self, **kwargs)

  File "/Users/JGTB/opt/anaconda3/lib/python3.7/site-packages/pyquery/pyquery.py", line 286, in _copy
    return self.__class__(*args, **kwargs)

  File "/Users/JGTB/opt/anaconda3/lib/python3.7/site-packages/pyquery/pyquery.py", line 271, in __init__
    xpath = self._css_to_xpath(selector)

  File "/Users/JGBT/opt/anaconda3/lib/python3.7/site-packages/pyquery/pyquery.py", line 282, in _css_to_xpath
    return self._translator.css_to_xpath(selector, prefix)

  File "/Users/JGTB/opt/anaconda3/lib/python3.7/site-packages/cssselect/xpath.py", line 192, in css_to_xpath
    for selector in parse(css))

  File "/Users/JGTB/opt/anaconda3/lib/python3.7/site-packages/cssselect/parser.py", line 415, in parse
    return list(parse_selector_group(stream))

  File "/Users/JGBT/opt/anaconda3/lib/python3.7/site-packages/cssselect/parser.py", line 428, in parse_selector_group
    yield Selector(*parse_selector(stream))

  File "/Users/JGTB/opt/anaconda3/lib/python3.7/site-packages/cssselect/parser.py", line 454, in parse_selector
    next_selector, pseudo_element = parse_simple_selector(stream)

  File "/Users/JGTB/opt/anaconda3/lib/python3.7/site-packages/cssselect/parser.py", line 545, in parse_simple_selector
    "Expected selector, got %s" % (peek,))

  File "<string>", line unknown
SelectorSyntaxError: Expected selector, got <DELIM '=' at 6>

**Comment by Gallaecio** [comment]
`'div id="items" class="style-scope ytd-grid-renderer"><ytd-grid-playlist-renderer class="style-scope ytd-grid-renderer" lockup=""'` is not a valid CSS expression.
